### PR TITLE
Code to ES6

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jescalan** [comment]
Hey @gkal19! Thanks for the contribution 😁 

So, this is not compatible with the current stable version of node, so I'm not sure I'd be willing to put this out. I'd be happy to hear the other side though!

**Comment by ghost** [comment]
@jescalan 
I understand! I had not even noticed Travis's errors

**Comment by jescalan** [comment]
At the moment, there is no node library that is ready to be converted to es modules. For client libraries, some bundlers such as webpack support es modules, but others don't so the best approach is to offer an es module build as well as a UMD build.

**Comment by ghost** [comment]
I understand. I'll close this Pull Request.
If you need help, just call me.

**Comment by jescalan** [comment]
Absolutely, thank you for the contribution! I really appreciate it. If you have any ideas for reshape features, I'd be happy to talk about them 😁

**Comment by ghost** [comment]
I got it!

**Pull request closed without merging**
