### PR TITLE
To determine the name of the processor

### PR DESCRIPTION
**Pull request by Scrum**
see https://github.com/posthtml/posthtml/pull/196

### CODE REVIEW

**Comment by jescalan** [comment]
Hi @GitScrum -- thanks for the PR! I don't entirely understand the use case for this though. Could you explain it a little more clearly for me?

**Comment by Scrum** [comment]
@jescalan Hi.
`this.name` need for correct detection type processor which I use in [post-load-plugins](https://github.com/post-org/post-load-plugins). - Automatically collect plugins and configuration for plugins for loads/preparation.

`this.version` need for 
```js
if ( opt.processor.version.split('.')[0] !== '1' ) {
  throw new Error('This plugin works only with Reshape 1');
}
```
I can determine the type of processor one and properties in the options but it is incorrect ((

```node
plugins: [ [Function] ],
parser: [Function: ReshapeParser],
generator: [Function: ReshapeCodeGenerator],
runtime: {},
ReshapeError: { [Function: ReshapeError] generatePluginError: [Function] },
PluginError: [Function: ReshapePluginError]
```

[more discussion](https://github.com/postcss/postcss/pull/932)

**Comment by jescalan** [comment]
Ok, makes more sense to me now. I just made a slight modification to the options -- named the option `meta` since it contains metadata on the processor, and made it such that the `meta` option only includes the relevant information.

Does this look ok to you?

**Comment by Scrum** [comment]
Ok, don't mind if the `meta` is going to leave the `processor` ? Because `posthtml` and `postcss` use this name.

**Comment by jescalan** [comment]
If they both do I guess it's ok. It's not exactly accurate naming though, but 🤷‍♂️

**Pull request merged**
