### PR TITLE
Overdue dependency updates

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
Just as with [reshape-layouts/#25](https://github.com/reshape/layouts/pull/25) I did an overdue update of the dependencies. I only had to add 2 spaces to make the linter happy, the rest updated without breaking anything.

There is however a different problem I encountered (which is the reason this is a draft-PR): the tests are currently failing. I have no idea why travis says everything is fine, without any modifications the `plugin error within a plugin` test fails.
I have determined the cause of this failure to be two things:
- It doesn't handle windows paths correctly. The regex looks for a path like `/a/b` when on windows (at least with cygwin) the path looks like this: `\\A\\B`. This could probably be solved by adding path normalization somewhere, but I have no idea where.
- The `Location` part of the regex is incorrect. It looks for a `\n` where there's only a space and everything after the second-last newline is not actually in the output (`\s\s2 | \n`)

For now I have changed the regex in a way that it works on *my machine*, but this most likely won't work on anything other than windows. If you can give me some pointers on where I should look to fix this in a non-hacky way I'll of course add (and rebase) it into the PR.

### CODE REVIEW

**Comment by jescalan** [comment]
First of all, this is awesome, and thank you. Great contribution, nice clear explanation. Just the type of thing I love to see!

So what I would actually do here to fix the issue is make the regex more generic -- don't have it check the full string but just for a couple key pieces that ensure that the correct error is being thrown in general. It's not important that we catch any tiny difference in spacing or formatting, what matters is that we catch that the correct error is being shown to users.

In my mind, the more generic/loose you can make a test and still have it test your logic just as soundly, the better 😀

**Comment by HoldYourWaffle** [comment]
I changed the test so that it looks for certain crucial information in the error message. Currently this is the error message, plugin name and basic location information.
I didn't include the '^' pointer line because I feel like that's too whitespace-sensitive. If you think it's important enough to be tested (part of me thinks it is) just let me know and I'll add it.

**Comment by jescalan** [comment]
Great, that looks just as I was imagining. I'll get this PR shipped out shortly, thank you so much and big 🎉 for the first contribution!

**Comment by HoldYourWaffle** [comment]
@jescalan #77, #76, #75, #74, #72 and #58 can be closed now.

**Comment by HoldYourWaffle** [comment]
@jescalan would it be possible for you to publish these changes to npm? It would save me a lot of headaches while trying to update some plugins 😄

**Comment by jescalan** [comment]
done, sorry for the delay!

**Pull request merged**
